Repository sofastack/sofa-dashboard-client, pull requests merged in 2019-08, with the labels that each got.

#22 Modify the readiness judgment strategy
  core/src/main/java/com/alipay/sofa/dashboard/client/registry/zookeeper/ZookeeperConstants.java
  sofa-boot-starter/pom.xml
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/listener/SofaDashboardContextRefreshedListener.java
  sofa-boot-starter/src/test/java/com/alipay/sofa/dashboard/client/listener/SofaDashboardContextRefreshedListenerTest.java
  sofa-boot-starter/src/test/resources/application.properties
Labels: cla:yes, size/M

#24 Sign up biz state
  core/pom.xml
  core/src/main/java/com/alipay/sofa/dashboard/client/common/Constants.java
  core/src/main/java/com/alipay/sofa/dashboard/client/registry/zookeeper/ZookeeperAppPublisher.java
  core/src/main/java/com/alipay/sofa/dashboard/client/registry/zookeeper/ZookeeperRegistryClient.java
  core/src/main/java/com/alipay/sofa/dashboard/client/utils/JsonUtils.java
  core/src/test/java/com/alipay/sofa/dashboard/client/base/TestBase.java
  core/src/test/java/com/alipay/sofa/dashboard/client/registry/ZookeeperRegisterSubscribeTest.java
  core/src/test/java/com/alipay/sofa/dashboard/client/registry/ZookeeperRegistryBasicTest.java
  core/src/test/java/com/alipay/sofa/dashboard/client/registry/ZookeeperRegistryRecoverTest.java
  sofa-boot-starter/pom.xml
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/config/AppPublisherConfiguration.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/config/BizStateConfiguration.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/listener/BizStateListener.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/listener/SofaDashboardContextClosedListener.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/listener/SofaDashboardContextRefreshedListener.java
  sofa-boot-starter/src/main/resources/META-INF/spring.factories
  sofa-boot-starter/src/test/java/com/alipay/sofa/dashboard/client/listener/SofaDashboardContextRefreshedListenerTest.java
  sofa-boot-starter/src/test/resources/application.properties
Labels: cla:yes, size/XL

#25 fix-bizStateListener-in-non-ark-env
  .travis.yml
  core/pom.xml
  core/src/main/java/com/alipay/sofa/dashboard/client/registry/zookeeper/ZookeeperAppPublisher.java
  core/src/main/java/com/alipay/sofa/dashboard/client/utils/JsonUtils.java
  pom.xml
  sofa-boot-starter/pom.xml
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/config/BizStateConfiguration.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/listener/BizStateListener.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/listener/SofaDashboardContextRefreshedListener.java
  sofa-boot-starter/src/main/java/com/alipay/sofa/dashboard/client/properties/SofaDashboardZookeeperProperties.java
Labels: bug, cla:yes, size/M
